title: "Utilities"
status: "ready"
root: true
collated: false
context:
    flexText:
        - "One"
        - "Two"
        - "Three"
        - "Four"
        - "Five"
    borders:
        - side: top
        - side: right
        - side: bottom
        - side: left
        - side: all
        - side: all
          radius: true
    spacings:
        - abbr: -xxs
          rem: .25
          pixels: 4
          name: Extra extra small
        - abbr: -xs
          rem: .5
          pixels: 8
          name: Extra small
        - abbr: -sm
          rem: 1
          pixels: 16
          name: Small
        - abbr: -md
          rem: 1.5
          pixels: 24
          name: Medium
        - abbr: -lg
          rem: 2
          pixels: 32
          name: Large
        - abbr: -xl
          rem: 2.5
          pixels: 40
          name: Extra large
        - abbr: -xxl
          rem: 3
          pixels: 48
          name: Extra extra large
    texts:
        - abbr: -regular
          name: Regular
        - abbr: -bold
          name: Bold
        - abbr: -uppercase
          name: Uppercase
        - abbr: -left
          name: Left
        - abbr: -center
          name: Center
        - abbr: -right
          name: Right
    typeScale:
        - abbr: -xxs
          rem: .75
          pixels: 12
        - abbr: -xs
          rem: .875
          pixels: 14
        - abbr: -base
          rem: 1
          pixels: 16
        - rem: 1.125
          pixels: 18
        - abbr: -sm
          rem: 1.25
          pixels: 20
        - rem: 1.4375
          pixels: 23
        - abbr: -md
          rem: 1.625
          pixels: 26
        - rem: 1.8125
          pixels: 29
        - abbr: -lg
          rem: 2
          pixels: 32
        - rem: 2.25
          pixels: 36
        - abbr: -xl
          rem: 2.5625
          pixels: 41
        - rem: 2.875
          pixels: 46
        - abbr: -xxl
          rem: 3.25
          pixels: 52
    typeScaleText: Lorem ipsum
    colors:
        - variable: white
          hex: "ffffff"
        - variable: cream
          hex: "edebeb"
        - variable: crimson
          hex: "990000"
        - variable: black
          hex: "243142"
        - variable: black-000
          hex: "f7f7f8"
        - variable: black-100
          hex: "ebecee"
        - variable: black-200
          hex: "c4c7cc"
        - variable: black-300
          hex: "a7abb3"
        - variable: black-400
          hex: "8b919b"
        - variable: black-500
          hex: "707784"
        - variable: black-600
          hex: "565f6d"
        - variable: black-700
          hex: "3d4757"
        - variable: black-800
          hex: "243142"
        - variable: black-900
          hex: "161c24"
        - variable: blue
          hex: "006298"
        - variable: blue-000
          hex: "edf1f6"
        - variable: blue-100
          hex: "dce3ee"
        - variable: blue-200
          hex: "b8c8dc"
        - variable: blue-300
          hex: "95adcb"
        - variable: blue-400
          hex: "7194ba"
        - variable: blue-500
          hex: "497ba9"
        - variable: blue-600
          hex: "006298"
        - variable: blue-700
          hex: "134a71"
        - variable: blue-800
          hex: "16324b"
        - variable: blue-900
          hex: "121c28"
        - variable: green
          hex: "008a28"
        - variable: green-000
          hex: "eaf3e8"
        - variable: green-100
          hex: "d4e8d2"
        - variable: green-200
          hex: "aad1a7"
        - variable: green-300
          hex: "7eb97c"
        - variable: green-400
          hex: "50a253"
        - variable: green-500
          hex: "008a28"
        - variable: green-600
          hex: "116d23"
        - variable: green-700
          hex: "16521d"
        - variable: green-800
          hex: "153717"
        - variable: green-900
          hex: "111f0f"
        - variable: yellow
          hex: "f5bb17"
        - variable: yellow-000
          hex: "ffeecd"
        - variable: yellow-100
          hex: "ffdd9b"
        - variable: yellow-200
          hex: "d6a31a"
        - variable: yellow-300
          hex: "b58a1b"
        - variable: yellow-400
          hex: "94721b"
        - variable: yellow-500
          hex: "f5bb17"
        - variable: yellow-600
          hex: "765a19"
        - variable: yellow-700
          hex: "584416"
        - variable: yellow-800
          hex: "3c2e13"
        - variable: yellow-900
          hex: "221b0c"
        - variable: orange
          hex: "df3603"
        - variable: orange-000
          hex: "ffece5"
        - variable: orange-100
          hex: "ffd9cc"
        - variable: orange-200
          hex: "ffb49a"
        - variable: orange-300
          hex: "fa8e6b"
        - variable: orange-400
          hex: "ef663c"
        - variable: orange-500
          hex: "df3603"
        - variable: orange-600
          hex: "b02f0a"
        - variable: orange-700
          hex: "82270d"
        - variable: orange-800
          hex: "571e0c"
        - variable: orange-900
          hex: "2f1407"
    zIndexes:
        - number: 1000
        - number: 900
        - number: 800
        - number: 700
        - number: 600
        - number: 500
        - number: 400
        - number: 300
        - number: 200
        - number: 100
        - number: 0