title: Dialog
status: "ready"
collated: true
context:
  buttonText: "Non-modal dialog"
  id: "dialogExample"
  dialogTitleId: "dialog-example-title"
  dialogTitle: "Dialog Title"
  dialogBody: <p>The default non-modal dialog sits on top of the page content and isn't dismissed when the user clicks outside of it. A developer can use special CSS classes to position the dialog at a corner of the page instead of the middle.</p>
  controls:
    - text: "I want to continue"
      attributes:
        - label: "role"
          value: "button"
    - text: "No"
      attributes:
        - label: "data-rvt-dialog-close"
          value: "dialogExample"
        - label: "role"
          value: "button"
    - text: "No, please cancel"
      attributes:
        - label: "data-rvt-dialog-close"
          value: "dialogExample"
        - label: "role"
          value: "button"
variants:
  - name: "with-form"
    context:
      buttonText: "Non-modal dialog with form"
      id: "dialogWithForm"
      formId: "test-form"
      dialogFormTitle: "dialog-form-title"
      dialogBody: <div class="m-bottom-sm"><label class="rvt-label" for="the-title">Title</label><input class="rvt-text-input" type="text" id="the-title"></div><label class="rvt-label" for="description">Description</label><textarea class="rvt-textarea" id="description"></textarea><fieldset class="rvt-fieldset"><legend class="rvt-ts-23 rvt-m-bottom-sm"><strong>Select dropdown</strong> default</legend><label class="rvt-label" for="select-demo">Select input:</label><select class="rvt-select m-bottom-md" id="select-demo"><option value="">Option One</option><option value="">Option Two</option><option value="">Option Three</option><option value="">Option Four</option></select></fieldset><fieldset class="rvt-fieldset rvt-m-top-xl"><legend class="rvt-ts-20 rvt-text-bold">Category</legend><ul class="rvt-list-plain"><li><input class="rvt-checkbox" type="checkbox" name="checkbox-demo" id="checkbox-3"><label class="rvt-label" for="checkbox-3" class="m-right-sm">Option one</label></li><li><input class="rvt-checkbox" type="checkbox" name="checkbox-demo" id="checkbox-4"><label class="rvt-label" for="checkbox-4">Option two</label></li><li><input class="rvt-checkbox" type="checkbox" name="checkbox-demo" id="checkbox-4-disable" disabled><label class="rvt-label" for="checkbox-4-disable">Option three disabled</label></li><li><input class="rvt-checkbox" type="checkbox" name="checkbox-demo" id="checkbox-5" disabled checked><label class="rvt-label" for="checkbox-5">Option four checked and disabled</label></li></ul></fieldset>
      controls:
        - text: OK
          attributes:
            - label: "role"
              value: "button"
        - text: Cancel
          attributes:
            - label: "data-rvt-dialog-close"
              value: "dialogWithForm"
            - label: "role"
              value: "button"
  - name: "modal-dialog"
    context:
      modal: true
      disablePageInteraction: true
      buttonText: "Modal dialog"
      id: "modalDialogExample"
      dialogTitleId: "modal-dialog-title"
      dialogTitle: "Modal Dialog"
      dialogBody: "<p>A modal dialog sits on top of the content and darkens the page behind it. The user can dismiss it by clicking anywhere outside the dialog or by using the close buttons.</p>"
      controls:
        - text: "Yes"
          attributes:
            - label: "role"
              value: "button"
        - text: "No, thanks"
          attributes:
            - label: "data-rvt-dialog-close"
              value: "dialogDialogExample"
            - label: "role"
              value: "button"
